# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quinten Mares Projects
email: quinten@mares.be
description: > # this means to ignore newlines until "baseurl:"
  This is my project page with somme of my own projects. Mostly coded in
  HTML, CSS and javascript. I do like the the idea of creating en sharing
  without any earingmodel behind it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://quinten.mares.be" # the base hostname & protocol for your site
twitter_username: Quinten_Mares
github_username:  quintenm

# Build settings
markdown: kramdown
